#cloud-config
users:
- name: root
  gecos: root user
  shell: /bin/bash
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJbpjhYB2/wlBUl9eoULOVYNVcOYHSw8QhADHn2p72v1VMW4shNhjVmoCg7+mWN/LfR+f+RcqXFRX9l4G3CH38xOgRtBmQ6dNBXrEHzdrDP7BY/Bdscmjkqa2XPNgxJeY7kPcSSEkNqU1E+0END+3m27NoltL8J+zZyVwOWH2vJeEYiaWYn4A5uYf0c1dyjXuYv/8rxgt/tuVYbhho+M0T94l+KyoVRkAIOq5kkDR983I9oN3/g1FBedn4eay1+rVhztpFIBLplppea9/B7q7O1SW4TidxFO57rgNU673swM1O8fQ0aLQ4293SJlpZK7IoBiKZc2iwsDn4y23nrgnFkwNr5PSVoXh4tQJZTZ6l3HJvPguu4bFwnAsXJGiQWoVwf+SPx2VaaDPfEXk2Lw011QT8bu27Uh6JB7cLvtqpO+lKsHWzGSFV1Md0LiXui0zziOxEs+b+K7/EOV0M5YNhj2KDNNSp5nO+utQB9rWqZ8+68DLotwq4s4Z7gyyJ6hbvcCqUD7Y8SKJoh656oCw54kQELb9OqFRssKJlhpmKYoEsH3Ij8p0yezetl/LN6jdQmbig1mQMXQnBGCYXtyyZrllB9hEMeiyeKzJJURr3x5qajEsP8VUM/6Or/H7VwhPttp+vbkRoOkwxvQf75OA6H6V9NEPVpOtOPX76oi7Xgw== amigoigna@gmail.com
package_update: true
package_upgrade: true
packages:
  - git
  - awscli
  - vim
  - python3-boto 
  - python3-pip
  - python3-dev
  - librsync-dev
  - gettext
  - build-essential
  - zip
  - unzip
  - ansible

runcmd:

  # Install postgres
  - echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  - apt update -y
  - apt install -y postgresql-14

  # Add iex function
  - echo -e "iex0 () {\n\t iex 0 \n}" >> /root/.bashrc
  - echo -e "iex() {\n\tssh mevaterapia-production-"\$1" /root/mevaterapia/_build/prod/rel/mevaterapia/bin/mevaterapia remote \n}" >> /root/.bashrc

  # Install duplicity
  - git clone https://gitlab.com/duplicity/duplicity.git --branch rel.2.1.2 && cd duplicity && pip3 install -r requirements.txt --break-system-packages && python3 setup.py install && rm -rf /root/duplicity/
